### ISSUE TITLE
Support ruby 2.2

### ISSUE THREAD

**Issue by bsutherland** [jenseng/hair_trigger#40]
I guess this may be caused by the ruby_parser dependency not supporting 2.2?

`Error reading triggers in db/migrate/20150415070431_create_trigger_user_update.rb: unrecognized RUBY_VERSION 2.2.0`

**Comment by jenseng** [comment]
Yeah, unfortunately even the latest ruby_parser still just supports 2.1. This might be a good time to investigate swapping it out for [parser](https://github.com/whitequark/parser), which does support 2.2 ... I've been meaning to check it out for a while now.

**Comment by bsutherland** [comment]
For anyone with the same issue, here's a nasty monkey patch which works for now, based on someone else's earlier patch when the same issue happened with Ruby 2.1:

If you're using Rails, you can put this in config/initializers/overrides.rb

```ruby
require 'ruby_parser'

# Monkey patch to support Ruby 2.2
RubyParser.class_eval do
  def self.for_current_ruby
    Ruby21Parser.new
  end
end
```

**Comment by jtippett** [comment]
+1 to this, but I do note that ruby_parser seems to be inching towards supporting 2.2

**Comment by monkbroc** [comment]
FYI, I installed `hair_trigger` in an app with Ruby 2.2.1 and its working fine. Bundler pulled in `ruby_parser` 3.7.0 which has preliminary support for Ruby 2.2. It seems to be enough.

Do you want to close this issue @jenseng?

**Comment by jenseng** [comment]
i'll bump the ruby_parser dependency and then close this out. thanks :)

**Comment by mockdeep** [comment]
Bump on this. It's blocking us upgrading to Ruby 2.2.

**Comment by jenseng** [comment]
dang, I spaced on this on in the last hairtrigger release /o\ ... stand by

**Comment by jenseng** [comment]
ruby_parser dependency has been bumped in v0.2.17

**Comment by mockdeep** [comment]
Great, thanks! Will give that a shot.
