### ISSUE TITLE
Rails 5.0.1: "alias_method_chain is deprecated"

### ISSUE THREAD

**Issue by jmcnevin** [jenseng/hair_trigger#59]
I see the following warning when starting my Rails 5.0.1 app:

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at .../config/application.rb:13)
.../hairtrigger-0.2.19/lib/hair_trigger/migrator.rb:20:in `block in included'
  .../hairtrigger-0.2.19/lib/hair_trigger/migrator.rb:19:in `instance_eval'
  .../hairtrigger-0.2.19/lib/hair_trigger/migrator.rb:19:in `included'
  .../hairtrigger-0.2.19/lib/hair_trigger.rb:224:in `include'
  .../hairtrigger-0.2.19/lib/hair_trigger.rb:224:in `<top (required)>'
```

**Comment by jmcnevin** [comment]
I see a similar warning from `schema_dumper.rb:100` as well.

**Comment by miltzi** [comment]
@jenseng Are there any plans to fix this? I tried cloning the repo to see if I could fix it myself but I'm not familiar with `alias_method_chain` and got quite lost.

**Comment by miltzi** [comment]
@jenseng I did some further reading and think I have managed to reproduce the functionality using `Module#prepend`
#61

**Comment by ribanez7** [comment]
Is anyone working on this issue? Thanks!

**Comment by jenseng** [comment]
PR has been merged, I'll cut a new release in the next few days. Thanks @miltzi!

**Comment by barthez** [comment]
![](https://media3.giphy.com/media/ALalVMOVR8Qw/200_s.gif)
@jenseng woulnd't you mind to release it soon? Please 😄

**Comment by jenseng** [comment]
Sorry for the delay, doing some housekeeping on this gem right now and will publish a new version
