### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported in Rails 5.1

### ISSUE THREAD

**Issue by minhth1905** [jenseng/hair_trigger#67]
Hi there - thanks for the great gem.
I used and had an error `Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: 
 class ..... < ActiveRecord::Migration[4.2]`
when run `rake db:generate_trigger_migration` in rails 5.1.2

**Comment by jenseng** [comment]
👍 Thanks for the bug report, this has been fixed on master as of a few minutes ago (#64) ... I'm about to push a new version with the fix

**Comment by jenseng** [comment]
Give [0.2.20](https://rubygems.org/gems/hairtrigger/versions/0.2.20) a spin, that should solve the issue 🤞
