### ISSUE TITLE
How to execute sequence with prefix

### ISSUE THREAD

**Issue by olimart** [jenseng/hair_trigger#69]
Hi @jenseng 

Could you explain how to create a trigger on insert matching prefix + sequence pattern?
Let's say I want to have my `tickets` table to have a `ref` column with `TICK000 + id`

Thanks. This is what I have so far.

```ruby
trigger.after(:insert) do
  ref = "TICK000"
  "UPDATE tickets SET reference = ref + id WHERE id = NEW.id;"
end
```

**Comment by jenseng** [comment]
Hi @olimart, if I'm understanding correctly, the reference column should be the `id`, prefixed with some value? e.g. if `id = 123`, then `ref = "TICK000123"`?

In that case, you could do something like this:

```ruby
trigger.after(:insert) do
  # `||` is the string concatenation operator in sql (all engines except mysql)
  # for mysql, you'd want `CONCAT('TICK000', id)`
  "UPDATE tickets SET reference = 'TICK000' || id WHERE id = NEW.id;"
end
```

**Comment by olimart** [comment]
ok thanks I'll give it a try.
