### ISSUE TITLE
Fix Ruby 2.7 warnings

### ISSUE THREAD

**Issue by erikaxel** [jenseng/hair_trigger#89]
Im getting a Ruby 2.7 warning. 
`hair_trigger/builder.rb:145: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
hair_trigger/builder.rb:155: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
(I get this multiple times each time we run db:migrate)

**Comment by imaqsood** [comment]
#91

**Comment by jenseng** [comment]
Fixed in #90, pushing a new release shortly
